[build]
# For Netlify deployment, the public_url should be the root.
public_url = "/"
dist = "docs"

[serve]
# These headers are required for SharedArrayBuffer to work, which is needed for wasm-bindgen-rayon.
headers = { Cross-Origin-Opener-Policy = "same-origin", Cross-Origin-Embedder-Policy = "require-corp" }
